# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#   test_mac:
#     strategy:
#       matrix:
#         platform: [ macos-latest ]
#         node-version: [ 10.16.3 ]
#     runs-on: ${{ matrix.platform }}

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm install
#     - run: npm run test
  test_linux:
#     needs: test_mac
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node-version: [ 10.16.3 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: import test with --import option
        run: npm run test src/tests/importWithOption
      - name: import test without --import option
        run: npm run test src/tests/importWithoutOption
      - name: export test with --export option
        run: npm run test src/tests/exportWithOption
      - name: export test without --export option
        run: npm run test src/tests/exportWithoutOption
#   test_windows:
#     needs: [ test_mac, test_linux ]
#     strategy:
#       matrix:
#         platform: [ windows-2016 ]
#         node-version: [ 10.16.3 ]
#     runs-on: ${{ matrix.platform }}

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: npm install
#       - run: npm run test
